config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'welcome/index'
  resources :incomes
  resources :reports
  resources :categories
  resources :expenses
  root 'welcome#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  layout "welcome"
  def index
  end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/welcome/index.html.erb
<div class="d-flex align-items-end justify-content-center" style="height: 400px">
    <h1>Welcome to Finance Manager</h1>
</div>
<% if user_signed_in? %>
    <form class="form-inline d-flex align-items-center justify-content-center">
        <div style="padding-left: 10px;">
            <%= link_to 'Incomes', incomes_path, class: "btn btn-outline-info" %>
        </div>
        <div style="padding-left: 10px;">
            <%= link_to 'Expenses', expenses_path, class: "btn btn-outline-success" %>
        </div>
        <div style="padding-left: 10px;">
            <%= link_to 'Categories', categories_path, class: "btn btn-outline-primary" %>
        </div>
        <div style="padding-left: 10px;">
            <%= link_to 'Generate Report', reports_path, class: "btn btn-outline-warning" %>
        </div>
    </form>
<% else %>
    <form class="form-inline d-flex align-items-center justify-content-center">
        <div style="padding-left: 10px;">
            <%= link_to 'Login', new_user_session_path, class: "btn btn-outline-info" %>
        </div>
        <div style="padding-left: 10px;">
            <%= link_to 'Sign up', new_user_registration_path, class: "btn btn-outline-success" %>
        </div>
<% end %>