config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'welcome/index'
  resources :incomes
  resources :reports
  resources :categories
  resources :expenses
  root 'welcome#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/income.rb
class Income < ApplicationRecord
  belongs_to :user
  belongs_to :category # belong to one category
end

app/controllers/incomes_controller.rb
class IncomesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_income, only: [:show, :edit, :update, :destroy]

  # GET /incomes
  # GET /incomes.json
  def index
    @incomes = Income.all
  end

  # GET /incomes/1
  # GET /incomes/1.json
  def show
  end

  # GET /incomes/new
  def new
    @income = Income.new
  end

  # GET /incomes/1/edit
  def edit
  end

  # POST /incomes
  # POST /incomes.json
  def create
    @income = current_user.incomes.build(income_params)

    respond_to do |format|
      if @income.save
        format.html { redirect_to @income, notice: 'Income was successfully created.' }
        format.json { render :show, status: :created, location: @income }
      else
        format.html { render :new }
        format.json { render json: @income.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /incomes/1
  # PATCH/PUT /incomes/1.json
  def update
    respond_to do |format|
      if @income.update(income_params)
        format.html { redirect_to @income, notice: 'Income was successfully updated.' }
        format.json { render :show, status: :ok, location: @income }
      else
        format.html { render :edit }
        format.json { render json: @income.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /incomes/1
  # DELETE /incomes/1.json
  def destroy
    @income.destroy
    respond_to do |format|
      format.html { redirect_to incomes_url, notice: 'Income was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_income
      @income = Income.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def income_params
      params.require(:income).permit(:category_id, :amount, :date, :description)
    end
end

app/helpers/incomes_helper.rb
module IncomesHelper
end

app/views/incomes/_form.html.erb
<%= form_with(model: income) do |form| %>
  <% if income.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(income.errors.count, "error") %> prohibited this income from being saved:</h2>

      <ul>
        <% income.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <form>
    <div class="form-group row">
    <div class="col-sm-1 col-form-label">
      <%= form.label :category_id %>
      </div>
      <div class="col-sm-3">
      <%= form.select(:category_id, options_from_collection_for_select(current_user.categories.all, :id, :name), { :prompt => 'Select a Category' }, { class: 'form-control', :required => true }) %>
      </div>
    </div>

    <div class="form-group row">
      <div class="col-sm-1 col-form-label">
      <%= form.label :amount %>
      </div>
      <div class="col-sm-3">
      <%= form.number_field :amount, step: 0.01, min: 0, class: "form-control", placeholder: "1, 25.5, 100, etc.", :required => true %>
      </div>
    </div>

    <div class="form-group row">
      <div class="col-sm-1 col-form-label">
      <%= form.label :date %>
      </div>
      <div class="col-sm-3">
      <%= form.text_field :date, class: 'form-control flatpickr', placeholder: "Select a Date" %>
      </div>
    </div>

    <div class="form-group row">
      <div class="col-sm-1 col-form-label">
      <%= form.label :description %>
      </div>
      <div class="col-sm-3">
      <%= form.text_field :description, class: "form-control", placeholder: "Salary, Ebay, Sales, etc.", :required => true %>
      </div>
    </div>

    <div class="form-group">
      <div class="row col-sm-3">
      <%= form.submit "Save", class: "btn btn-outline-success" %>
      </div>
    </div>
  </form>
<% end %>

app/views/incomes/edit.html.erb
<div class="container">
<h1>Editing Income</h1>

<%= render 'form', income: @income %>

<%= link_to 'Show', @income, class: "btn btn-outline-info" %>
<%= link_to 'Back', incomes_path, class: "btn btn-outline-primary" %>
</div>

app/views/incomes/index.html.erb
<div class="container">

<h1>Incomes</h1>

<div class="form-group">
<%= link_to 'New Income', new_income_path, class: "btn btn-outline-info" %>
</div>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Category</th>
      <th>Amount</th>
      <th>Date</th>
      <th>Description</th>
      <th>Actions</th>
    </tr>
  </thead>

  <tbody>
    <% current_user.incomes.each do |income| %>
      <tr>
        <td class="align-middle"><%= income.category %></td>
        <td class="align-middle"><%= income.amount %></td>
        <td class="align-middle"><%= income.date %></td>
        <td class="align-middle "><%= income.description %></td>
        <td><%= link_to 'Show', income, class: "btn btn-outline-info" %>
        <%= link_to 'Edit', edit_income_path(income), class: "btn btn-outline-success" %>
        <%= link_to 'Destroy', income, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-outline-danger" %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>

app/views/incomes/new.html.erb
<div class="container">
<h1>New Income</h1>

<%= render 'form', income: @income %>

<%= link_to 'Back', incomes_path, class: "btn btn-outline-primary" %>
</div>

app/views/incomes/show.html.erb
<div class="container">

<p>
  <strong>Category:</strong>
  <%= @income.category %>
</p>

<p>
  <strong>Amount:</strong>
  <%= @income.amount %>
</p>

<p>
  <strong>Date:</strong>
  <%= @income.date %>
</p>

<p>
  <strong>Description:</strong>
  <%= @income.description %>
</p>

<%= link_to 'Edit', edit_income_path(@income), class: "btn btn-outline-success" %>
<%= link_to 'Back', incomes_path, class: "btn btn-outline-primary" %>
</div>