config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'welcome/index'
  resources :incomes
  resources :reports
  resources :categories
  resources :expenses
  root 'welcome#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/category.rb
class Category < ApplicationRecord
    belongs_to :user
    has_many :expenses, dependent: :delete_all # can have many expenses
    has_many :incomes, dependent: :delete_all  # can have many incomes
    def to_s
        name
    end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = current_user.categories.build(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def category_params
      params.require(:category).permit(:name, :description)
    end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_form.html.erb
<%= form_with(model: category) do |form| %>
  <% if category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
        <% category.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <form>
    <div class="form-group row">
    <div class="col-sm-1 col-form-label">
      <%= form.label :name %>
      </div>
      <div class="col-sm-3">
      <%= form.text_field :name, class: "form-control", placeholder: "Groceries, Clothes, etc.", :required => true %>
      </div>
    </div>

    <div class="form-group row">
      <div class="col-sm-1 col-form-label">
      <%= form.label :description %>
      </div>
      <div class="col-sm-3">
      <%= form.text_field :description, class: "form-control", placeholder: "Category for..." %>
      </div>
    </div>

    <div class="form-group">
      <div class="row col-sm-3">
      <%= form.submit "Save", class: "btn btn-outline-success" %>
      </div>
    </div>
  </form>
<% end %>

app/views/categories/edit.html.erb
<div class="container">
<h1>Editing Category</h1>

<%= render 'form', category: @category %>

<%= link_to 'Show', @category, class: "btn btn-outline-info" %>
<%= link_to 'Back', categories_path, class: "btn btn-outline-primary" %>
</div>

app/views/categories/index.html.erb
<div class="container">

<h1>Categories</h1>

<div class="form-group">
<%= link_to 'New Category', new_category_path, class: "btn btn-outline-info" %>
</div>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Actions</th>
    </tr>
  </thead>

  <tbody>
    <% current_user.categories.each do |category| %>
      <tr>
        <td class="align-middle"><%= category.name %></td>
        <td class="align-middle"><%= category.description %></td>
        <td><%= link_to 'Show', category, class: "btn btn-outline-info" %>
        <%= link_to 'Edit', edit_category_path(category), class: "btn btn-outline-success" %>
        <%= link_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-outline-danger" %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>

app/views/categories/new.html.erb
<div class="container">
<h1>New Category</h1>

<%= render 'form', category: @category %>

<%= link_to 'Back', categories_path, class: "btn btn-outline-primary" %>
</div>

app/views/categories/show.html.erb
<div class="container">

<p>
  <strong>Name:</strong>
  <%= @category.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @category.description %>
</p>

<%= link_to 'Edit', edit_category_path(@category), class: "btn btn-outline-success" %>
<%= link_to 'Back', categories_path, class: "btn btn-outline-primary" %>
</div>